### PR TITLE
examples: make cards higher (allow 4 lines per cards)

### PR DESCRIPTION
**Pull request by rfourquet**
To accomodate upcoming notebook example (cf. #130).

### CODE REVIEW

**Comment by fingolfin** [comment]
Can we see a preview somewhere?

**Comment by rfourquet** [comment]
https://rfourquet.github.io/oscar-website/example/

(this preview also includes PR 130, i.e. the new notebook which has longer tittle than usual "A divisionally free not inductively free arrangement with a minimal number of hyperplanes")

**Review by mohamed-barakat — APPROVED** [review]

**Comment by mohamed-barakat** [comment]
Thank you very much. Looks nice.

**Comment by fingolfin** [comment]
Interesting. For me, this PR adds a lot of vertical whitespace in each card, but it doesn't really look to me as if it was needed for PR #130. Perhaps depends on which browser is used and where?

Screenshot 2020-07-20 at 16 18 10

**Comment by fingolfin** [comment]
(and yes, I did try resizing it back and forth)

**Comment by rfourquet** [comment]
In your picture, it looks like there is only one column of cards; when you have two columns, do you observe the same effect (unnecessary vertical space) ? 

For me, on the few browsers I tried, it looks like that:

pr130

But otherwise, when only one column is displayed, there is indeed more vertical space than necessary. I don't whether it's possible to change that.

**Comment by fingolfin** [comment]
OK, I see it now! Fine by me then!

**Review by fingolfin — APPROVED** [review]

**Pull request merged**
