### PR TITLE
added mardi page + sidebar link

### PR DESCRIPTION
**Pull request by antonydellavecchia**
Added a MaRDI page to the OSCAR webiste. Currently has a short description of MaRDI and has links to relevant information about the file format

### CODE REVIEW

**Comment by HereAround** [comment]
Thank you for adding this @antonydellavecchia . I just build this locally, and generally speaking the change looks good to me.

One issue though: The link to the mardi homepage (https://www.mardi-germany.de/) does not work. It receive "We can’t connect to the server at www.mardi-germany.de."

Is the server temporarily down? Or is there a typo in the link? Something different yet?

**Comment by HereAround** [comment]
For all it matters: I could so far only find the following website when searching for MaRDI: https://www.mardi4nfdi.de/about/mission.

**Comment by antonydellavecchia** [comment]
> Thank you for adding this @antonydellavecchia . I just build this locally, and generally speaking the change looks good to me.
> 
> One issue though: The link to the mardi homepage (https://www.mardi-germany.de/) does not work. It receive "We can’t connect to the server at [www.mardi-germany.de](http://www.mardi-germany.de)."
> 
> Is the server temporarily down? Or is there a typo in the link? Something different yet?

ah sorry, I generated part of that and didn't check the link. thanks for catching that.

**Review by HereAround — APPROVED** [review]
Good to go now. Thank you @antonydellavecchia

**Pull request merged**
