### PR TITLE
add examples filtering feature

### PR DESCRIPTION
**Pull request by rfourquet**
This tries to address the "filtering examples" part of #92.

As we have a static website (i.e. without javascript), I created a separate page for each category. If we want more refined filtering (e.g. according to two or more keywords), I'm afraid we would need to use javascript, but I mostly don't know about this, so better ideas are welcome.

Others will need to chime in order to decide which keywords we use, for now I simply used these implied by the logos. There is a "main example page" (with keyword "All") containing all examples, and subpages with filtered examples. 

Preview at https://rfourquet.github.io/oscar-website/exampleNEW/.

### CODE REVIEW

**Comment by fingolfin** [comment]
That's a good start, IMHO. But it should be changed so that the currently selected "filter" is highlighted (e.g. instead of being a link, it should be bold). We use a similar trick for the sidebar navigation, see `_includes/sidebar.html` (this is a fairly standard technique, so google should reveal plenty more examples how to do it in Jekyll).

**Comment by rfourquet** [comment]
> it should be changed so that the currently selected "filter" is highlighted 

Yes this was my plan, but I wanted to have feedback on the approach first before finalizing.

**Comment by mohamed-barakat** [comment]
Logo_CAP could be renamed into CAP.

**Comment by rfourquet** [comment]
> Logo_CAP could be renamed into CAP.

Yes this will of course be done. 

The current state of this PR is really not finalized, but before proceeding I wanted to have feedback on this filtering according to a category which can be mapped to "thumbnails".
I find it relatively intuitive for the user. But without javascript it's difficult to filter according to more than one categorization/keyword, so a decision needs to be made on which one.

**Comment by mohamed-barakat** [comment]
I think it is enough for now given the small about of notebooks so far.

**Comment by rfourquet** [comment]
I updated and finalized, preview now at https://rfourquet.github.io/oscar-website/example/.
As more notebooks are converted to using `Oscar` only, I don't know how this filtering will evolve, but this "provides the setup".

[EDIT: this is rebased on top of the "tiled examples" PR, which should be merged before this one]

**Comment by rfourquet** [comment]
I will merge later today if no objections.

**Pull request merged**
