### PR TITLE
Add more constraints to the gemfile

### PR DESCRIPTION
**Pull request by aaruni96**
This maintains compatibility with Ruby 3.3.5

### CODE REVIEW

**Comment by aaruni96** [comment]
@HereAround can you check if this works on your machine, i.e., that it does not break compatibility with an older version of ruby ? (I assume if you don't need these changes to run `jekyll serve`, you are on Ruby 3.2 ?)

**Comment by HereAround** [comment]
When I executed `bundle exec jekyll serve`, it lead to the following error:

```
Could not find gem 'sassc (= 2.1.0)' in locally installed gems.

The source contains the following gems matching 'sassc':
  * sassc-2.4.0
Run `bundle install` to install missing gems.
```

So I executed `bundle install`:

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Fetching logger 1.4.2
Fetching sassc 2.1.0 (x86_64-linux) (was 2.4.0)
Installing logger 1.4.2
Installing sassc 2.1.0 (x86_64-linux) (was 2.4.0)
Bundle complete! 8 Gemfile dependencies, 34 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

After this, `bundle exec jekyll serve` completes successfully and builds the website for me. Sadly though, `jekyll serve` - which I found very convenient - does not function any more after this change. (But this might not be the most important thing in the world.)

```
/home/i/gems/gems/bundler-2.5.4/lib/bundler/runtime.rb:304:in `check_for_activated_spec!': You have already activated sassc 2.4.0, but your Gemfile requires sassc 2.1.0. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /home/i/gems/gems/bundler-2.5.4/lib/bundler/runtime.rb:25:in `block in setup'
        from /home/i/gems/gems/bundler-2.5.4/lib/bundler/spec_set.rb:191:in `each'
        from /home/i/gems/gems/bundler-2.5.4/lib/bundler/spec_set.rb:191:in `each'
        from /home/i/gems/gems/bundler-2.5.4/lib/bundler/runtime.rb:24:in `map'
        from /home/i/gems/gems/bundler-2.5.4/lib/bundler/runtime.rb:24:in `setup'
        from /home/i/gems/gems/bundler-2.5.4/lib/bundler.rb:162:in `setup'
        from /home/i/gems/gems/jekyll-4.2.2/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
        from /home/i/gems/gems/jekyll-4.2.2/exe/jekyll:11:in `<top (required)>'
        from /home/i/gems/bin/jekyll:25:in `load'
        from /home/i/gems/bin/jekyll:25:in `<main>'
```

Long story short: I first had to install/update some packages on my machine. Only after that, `jekyll` could build the website on my system/machine.

**Comment by HereAround** [comment]
My ruby version:
```
ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
```

**Comment by aaruni96** [comment]
This is interesting: sassc 2.4 causes it to not build on my environment, but downgrading it to 2.1 (which makes it possible to build on my machine) requires you to do a bundle exec...

edit: you had to do a bundle install, which makes sense.

**Comment by aaruni96** [comment]
@fingolfin if you think this is sane, this can be merged.

**Comment by fingolfin** [comment]
Let's hope it doesn't break the web server, we'll find out...

**Comment by aaruni96** [comment]
So, this did break the web server...

```
update.sh[1962771]: You have requested:
update.sh[1962771]:   sassc = 2.1.0
update.sh[1962771]: The bundle currently has sassc locked at 2.4.0.
update.sh[1962771]: Try running `bundle update sassc`
update.sh[1962771]: If you are updating multiple gems in your Gemfile at once,
update.sh[1962771]: try passing them all to `bundle update`
systemd[1317]: oscar-website.service: Main process exited, code=exited, status=7/NOTRUNNING
systemd[1317]: oscar-website.service: Failed with result 'exit-code'.
systemd[1317]: Failed to start "Update OSCAR website".
```

Should I try running the bundle update manually? (In theory this should be a one time step, as either the bundle update will update `Gemfile.lock`, or we can manually remove the lockfile, and run bundle install. In any case, the new lockfile will have sassc=2.1.0)

**Pull request merged**
